# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential git -y
      - run: sudo apt-get install libudev-dev -y
      - run: sudo apt-get install libusb-1.0-0-dev -y
      - run: sudo apt-get install gcc-4.8 g++-4.8 -y
      - run: yarn install --frozen-lockfile
      - run: yarn test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: sudo apt-get update
      - run: sudo apt-get install build-essential git -y
      - run: sudo apt-get install libudev-dev -y
      - run: sudo apt-get install libusb-1.0-0-dev -y
      - run: sudo apt-get install gcc-4.8 g++-4.8 -y
      - run: yarn install --frozen-lockfile
      - run: npm run release --ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
